language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --no-suggest

script: php vendor/bin/phpunit --configuration phpunit.xml.dist

notifications:
    on_success: never
    on_failure: always
